# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .block_device import *
from .dns_domain import *
from .dns_record import *
from .fabric import *
from .get_fabric import *
from .get_subnet import *
from .get_vlan import *
from .instance import *
from .machine import *
from .network_interface_link import *
from .network_interface_physical import *
from .provider import *
from .space import *
from .subnet import *
from .subnet_ip_range import *
from .tag import *
from .user import *
from .vlan import *
from .vm_host import *
from .vm_host_machine import *
from ._inputs import *
from . import outputs

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "maas",
  "mod": "index/blockDevice",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/blockDevice:BlockDevice": "BlockDevice"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/dnsDomain",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/dnsDomain:DnsDomain": "DnsDomain"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/dnsRecord",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/dnsRecord:DnsRecord": "DnsRecord"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/fabric",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/fabric:Fabric": "Fabric"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/instance",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/machine",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/machine:Machine": "Machine"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/networkInterfaceLink",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/networkInterfaceLink:NetworkInterfaceLink": "NetworkInterfaceLink"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/networkInterfacePhysical",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/networkInterfacePhysical:NetworkInterfacePhysical": "NetworkInterfacePhysical"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/space",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/space:Space": "Space"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/subnet",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/subnet:Subnet": "Subnet"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/subnetIpRange",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/subnetIpRange:SubnetIpRange": "SubnetIpRange"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/tag",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/tag:Tag": "Tag"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/user",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/user:User": "User"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/vlan",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/vlan:Vlan": "Vlan"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/vmHost",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/vmHost:VmHost": "VmHost"
  }
 },
 {
  "pkg": "maas",
  "mod": "index/vmHostMachine",
  "fqn": "pulumi-maas",
  "classes": {
   "maas:index/vmHostMachine:VmHostMachine": "VmHostMachine"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "maas",
  "token": "pulumi:providers:maas",
  "fqn": "pulumi-maas",
  "class": "Provider"
 }
]
"""
)
