# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiKey: Optional[str]
"""
The MAAS API key
"""

apiUrl: Optional[str]
"""
The MAAS API URL (eg: http://127.0.0.1:5240/MAAS)
"""

apiVersion: Optional[str]
"""
The MAAS API version (default 2.0)
"""

